# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8a333cec4f2098c4950c0f8c25b4056e15a1fd4dccbde8259bcde5631dd3c3764a23e7ab1a0fe27e99da3b2a3082cc7cbe9704ba297f0417acfd338210c5459

test:
  secret_key_base: b113c3ec6d9770290f03947a25526e2b53d4813403a19e52f1d0b3da33f5511b327c7f9bb91227c2d79c19983576572b825404ee8fb8cf67df82e7ec33fb6483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
